baseURL = 'https://www.brunohensel.dev'
languageCode = 'en-us'
title = 'Bruno Hensel'
theme = 'hugo-coder' #'hello-friend-ng'
paginate = 10

[markup.highlight]
    noClasses = true
    style = "github-dark"

[params]
    author = "Bruno Hensel"
    description = "Android Software Engineer"
    info = ["Android Software Engineer"]
    avatarURL = "/logo.png"
    dateFormat = "Jan 2, 2006"
    colorScheme = "dark"
    hideColorSchemeToggle = true

[params.footer]
    trademark = true
    rss = true
    copyright = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url  = "https://github.com/brunohensel"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 2
    url  = "https://twitter.com/Brunohensel"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 3
    url  = "https://www.linkedin.com/in/bruno-hensel/"

[menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"