baseURL = 'http://brunohensel.dev'
languageCode = 'en-us'
title = 'Bruno Hensel'
theme = 'hello-friend-ng'
paginate = 10

[markup]
    [markup.highlight]
        noClasses = true
        style = 'base16-snazzy'

[params]
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    homeSubtitle = "Android Software Engineer"

[params.footer]
    trademark = true
    rss = true
    copyright = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Bruno Hensel"
        subtitle = "Android Software Engineer"
        keywords = ""
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

        [languages.en.params.logo]
            logoText = "Bruno Hensel"
            logoHomeLink = "/"


[params.portrait]
    path     = "/logo.png"
    alt      = "Portrait"
    maxWidth = "200px"

[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/Brunohensel"

[[params.social]]
    name = "github"
    url  = "https://github.com/brunohensel"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/bruno-hensel/"

[menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"