name: Build & Deploy
on:
  push:
    branches:
      - main # branch on which deploys take place
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      logLevel:
        description: 'Build & Deploy'
        required: true
        default: 'warning'
      tags:
        description: 'Build & Deploy'

# Allow only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: no # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.115.4 # hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: brunohensel/brunohensel.github.io
          publish_branch: main
          # Without `keep_files` the `CNAME` file in the target repo will get removed
          # and the custom domain configured for GitHub pages will get dropped every
          # time the action runs…
          keep_files: true
